language: elixir
elixir: 1.3.3
otp_release:
  - 18.2.1
sudo: false
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
before_script:
  - mix deps.get --only test
script:
  - npm run test-all
